language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"



jobs:
    fast_finish: true
    allow_failures:
        - python: "3.4"
        - python: "3.5"
        - python: "3.9"

install:
    - python -m pip install -r requirements.txt
    - python -m pip install -e .
    
script:
    - pytest


# deploy:
    # provider: pypi
    # user: "__token__"
    # on:
        # branch: release
    # skip_existing: true
